# This workflow will upload a Python Package to Release asset
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

# Needed to create release and upload assets
permissions:
  contents: write

jobs:
  release:
    # Retrieve tag and create release
    name: Create Release to github
    runs-on: self-hosted
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Extract branch info
        shell: bash
        run: |
          echo "release_tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"

      - name: Create Release
        id: create_release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          RELEASE_TAG: ${{ env.release_tag }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const script = require('.github/workflows/scripts/create_release.js')
            await script(github, context, core)

  wheel:
    name: Build Wheel
    runs-on: self-hosted
    container:
      image: vllm/vllm-openai:v0.9.2
    needs: release

    strategy:
      fail-fast: false
      matrix:
          os: ['ubuntu-20.04']
          python-version: ['3.12']
          pytorch-version: ['2.7.0']  # Must be the most recent version that meets requirements/cuda.txt.
          cuda-version: ['12.8.1']
          vllm-version: ['0.9.2']

    steps:
      - name: Setup proxy
        run: |
          export http_proxy="http://172.80.0.1:7890"
          git config --global http.sslVerify false
          export https_proxy=$http_proxy
          git config --global http.proxy $http_proxy
          git config --global https.proxy $https_proxy
          git config --global http.version HTTP/1.1

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@ed74d11c0b343532753ecead8a951bb09bb34bc9 # v1.2.14
        with:
          create-symlink: true
          key: ${{ github.job }}-${{ matrix.python-version }}-${{ matrix.cuda-version }}
  
      - name: Build wheel
        shell: bash
        env:
          CMAKE_BUILD_TYPE: Release # do not compile with debug symbol to reduce wheel size
        run: |
          export http_proxy="http://172.80.0.1:7890"
          git config --global http.sslVerify false
          export https_proxy=$http_proxy
          git config --global http.proxy $http_proxy
          git config --global https.proxy $https_proxy
          git config --global http.version HTTP/1.1
          
          export PLATFORM=cuda
          python3 setup.py bdist_wheel
          wheel_name=$(find dist -name "*whl" -print0 | xargs -0 -n 1 basename)
          asset_name=${wheel_name//"linux"/"manylinux1"}
          echo "wheel_name=${wheel_name}" >> "$GITHUB_ENV"
          echo "asset_name=${asset_name}" >> "$GITHUB_ENV"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./dist/${{ env.wheel_name }}
          asset_name: ${{ env.asset_name }}
          asset_content_type: application/*
  
  pypi_publish:
    name: Publish to PyPI
    runs-on: self-hosted
    needs: [release, wheel]
    environment: 
      name: testpypi
      url: https://test.pypi.org/p/ucm-test-release
    
    steps:
      - name: Download Release Asset
        uses: actions/download-artifact@v4.2.2
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          repository-url: https://test.pypi.org/legacy/
